apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: product-ui-build
spec:
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  source:
    git:
      ref: main
      uri: 'git@github.com:Client-Engineering-Industry-Squad-1-CD/products-ui.git'
    sourceSecret:
      name: gitsecret-2
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
    - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: 'product-ui:latest'