commonLabels:
  app: products-ms
configMapGenerator:
  - name: products-ms-config
    files:
    - application.properties
configurations:
  - configurations/nameReference.yaml
resources:
  - buildconfig.yaml
  - deploymentconfig.yaml
  - imagestream.yaml
  - service.yaml