apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-db-pvc
spec:
  storageClassName: ibmc-file-gold-gid
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi